image: alpine:latest

pages:
  stage: deploy
  script:
  - mkdir .public
  - cp index.html .public
  - cp -r .well-known .public
  - mv .public public  
  artifacts:
    paths:
    - public
  only:
  - master
